name:                pi-calculus-parser
version:             0.1.0.0
github:              "AdLucem/pi-calculus-parser"
license:             BSD3
author:              "Atreyee Ghosal"
maintainer:          "ghosalatreyee@gmail.com"
copyright:           "2018 Atreyee Ghosal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AdLucem/pi-calculus-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - parsec

executables:
  pi-calculus-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calculus-parser
    - parsec
